// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "4ec2498f-7cf2-43cc-b6ae-e4aaa8cc5b2c");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"on Windows but cannot usually use BITS\",\"not default profile\"]");
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1761068377);
user_pref("app.update.lastUpdateTime.background-update-timer", 1761068377);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1761068377);
user_pref("app.update.lastUpdateTime.region-update-timer", 1761068377);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1761068377);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1761068377);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1761068346);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 160);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b66f5d3c-1a25-425d-90a3-bdf6219c99f6}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20251009125714");
user_pref("browser.startup.homepage_override.mstone", "144.0");
user_pref("browser.startup.lastColdStartupCheck", 1761068349);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 3);
user_pref("captchadetection.lastSubmission", 1761068);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "422ef56a-7513-4234-be5e-8b8ae8f0de07");
user_pref("datareporting.dau.cachedUsageProfileID", "6a70fbec-48a7-4807-806c-b21a26634bc8");
user_pref("distribution.iniFile.exists.appversion", "144.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20251009125714");
user_pref("extensions.lastAppVersion", "144.0");
user_pref("extensions.lastPlatformVersion", "144.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"2861ffa8-a786-4ba8-a258-47aa82247588\",\"formautofill@mozilla.org\":\"a58d035c-7958-409a-b41d-d18e13c6049d\",\"ipp-activator@mozilla.com\":\"b6105e09-01ef-4d96-a363-e7dc893d8817\",\"pictureinpicture@mozilla.org\":\"a1cf3e02-3802-4163-ab33-7ed6603b7bc1\",\"addons-search-detection@mozilla.com\":\"b9998c23-4aaf-4eef-a220-14c8e81cd82d\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"888edd57-4f33-4271-bef9-72997c9bfa30\",\"default-theme@mozilla.org\":\"ba812f0c-3c87-4aca-b74b-dcc1a5f874eb\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20251009125714");
user_pref("gfx-shader-check.device-id", "0x9bc4");
user_pref("gfx-shader-check.driver-version", "31.0.101.1999");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "bba5e9c4-8f6e-4dcc-8100-43aeeb667e73");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x9bc4");
user_pref("sanity-test.driver-version", "31.0.101.1999");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20251009125714");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("telemetry.fog.init_on_shutdown", false);
user_pref("toolkit.profiles.storeID", "4f82bdf7");
user_pref("toolkit.startup.last_success", 1761068346);
user_pref("toolkit.telemetry.cachedClientID", "12e68d29-ff7b-4336-b4c3-a8916fc80bc6");
user_pref("toolkit.telemetry.cachedProfileGroupID", "6b3030ee-9e60-42a3-8dff-039a890bd491");
user_pref("toolkit.telemetry.previousBuildID", "20251009125714");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
