// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "3c5e5c8a-d859-491f-9f9a-d385eec78abf");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1761068725);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 160);
user_pref("browser.newtabpage.activity-stream.impressionId", "{836c3c1d-716b-474d-ba43-8a9e47b3c2eb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20251009125714");
user_pref("browser.startup.homepage_override.mstone", "144.0");
user_pref("browser.startup.lastColdStartupCheck", 1761068728);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 3);
user_pref("captchadetection.lastSubmission", 1761068);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "aec5d37c-3d1e-47e8-bd55-150d98b9b5cb");
user_pref("datareporting.dau.cachedUsageProfileID", "6e4140ef-3202-4e76-bd63-cec8163ad96e");
user_pref("distribution.iniFile.exists.appversion", "144.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20251009125714");
user_pref("extensions.lastAppVersion", "144.0");
user_pref("extensions.lastPlatformVersion", "144.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"56362e46-1dd8-4ccc-828d-7af467394338\",\"formautofill@mozilla.org\":\"6bdf675b-3bb7-471d-8ce5-0f1be6c167c2\",\"ipp-activator@mozilla.com\":\"6a56d109-38cf-4435-9779-b81c2463772f\",\"pictureinpicture@mozilla.org\":\"2f8f53ef-7f52-4b01-aeb7-c3db5dce3f0e\",\"addons-search-detection@mozilla.com\":\"3ce5971f-c210-49ff-ad0b-6b39c0bfce09\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"70765a88-77da-46a0-982c-23bbfdb19a10\",\"default-theme@mozilla.org\":\"afab7210-2b3b-4298-b0b9-735d2da15353\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20251009125714");
user_pref("gfx-shader-check.device-id", "0x9bc4");
user_pref("gfx-shader-check.driver-version", "31.0.101.1999");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "218124c7-c567-429b-b455-db7c72bb98a3");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x9bc4");
user_pref("sanity-test.driver-version", "31.0.101.1999");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20251009125714");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("telemetry.fog.init_on_shutdown", false);
user_pref("toolkit.profiles.storeID", "e8b25b21");
user_pref("toolkit.telemetry.cachedClientID", "da14c389-da24-4997-97bf-9d09ce1847e9");
user_pref("toolkit.telemetry.cachedProfileGroupID", "c8abd9fb-609d-4052-9966-c61630910966");
user_pref("toolkit.telemetry.previousBuildID", "20251009125714");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
